ICV_HOME_DIR      = /usr/local/synopsys/icvalidator/O-2018.12-SP2-9
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = mylibrary
INLIB_PATH        = 
BLOCK             = ringOscillator
PYDB_PATH         = run_details/pydb
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS = HIERARCHICAL
FORMAT            = OPENACCESS
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = rules.drc.9m_saed90_icv.drc.rs
