#! /bin/sh

echo $HOSTNAME | grep bender.engr.ucr.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 33123 
else 
rsh bender.engr.ucr.edu kill 33123 
 sleep 10 
rsh bender.engr.ucr.edu kill -9 33123 
fi
