ICV_HOME_DIR      = /usr/local/synopsys/icvalidator/O-2018.12-SP2-9
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = mylibrary
INLIB_PATH        = 
BLOCK             = ringOscillator
PYDB_PATH         = TOPCELLNAME_err
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS = HIERARCHICAL
FORMAT            = OPENACCESS
SCHEMATIC         = ringOscillator.sch_out
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = rules.lvs.9m_saed90_lvs.lvs.rs
ENVIRONMENT STRING  SAED90_PDK = /usr/local/synopsys/pdk/SAED_PDK90nm
EXTRACTION_FLOW   = true
COMPARE_DIR       = run_details/compare
COMPARE_NETLIST_FLOW = ICV
STATUS_COMPARE    = 0
WRITE_EQUIV_NETLISTS = ALL
