#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /home/tempmaj/kokurita/eecs168/pvjob_mylibrary.ringOscillator.icv.drc/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /home/tempmaj/kokurita/eecs168/pvjob_mylibrary.ringOscillator.icv.drc/ringOscillator.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /home/tempmaj/kokurita/eecs168/pvjob_mylibrary.ringOscillator.icv.drc/run_details/duse_master.tmp && \
mv /home/tempmaj/kokurita/eecs168/pvjob_mylibrary.ringOscillator.icv.drc/run_details/duse_master.tmp /home/tempmaj/kokurita/eecs168/pvjob_mylibrary.ringOscillator.icv.drc/run_details/duse_master
